### ISSUE TITLE
MFRC522 hexadecimal input

### ISSUE THREAD

**Issue by sohailahmadsgd** [Freenove/Freenove_RFID_Starter_Kit_for_Raspberry_Pi#3]
Hi
I am working on a project and want to enter Hexadecimal values for input data rather than ACII.
I am really new to RPi and also to Python. I dont know where to ask and how to get help.
Can someone help me with this

**Comment by SuhaylZhao** [comment]
Hi,

Can you describe your question in detail? Please send us screenshots or photos of your questions.

About our products, whether you have any questions, you can contact us by support@freenove.com

Thanks.

**Comment by sohailahmadsgd** [comment]
Hi Suhayl

I bought starter kit from Freenove because I have to do a project. I am new to RPi and to Python as well.
My project is related to MFRC522 RFID chip which is mentioned as project 24 in tutorial.
In this project we write on RFID chip using MFRC522. For this we run RFID.py file to read/write data on the RFID chip.
For writing we use these commands:
Scan --> Write 4 Hello World
Here "write" is for writing on chip
          "4" is the sector number
          "Hello World" is data 

My question is I want to enter Hexadecimal values directly rather than ASCII.

Can you help me to build a code or make changes in already written Python code so that instead of ASCII for data input I could put Hexadecimal values for data input.

Regards
Sohail Ahmad

**Comment by SuhaylZhao** [comment]
Hi,

Your ideas are good and easy to implement. But I'm sorry we can't accept your custom code requirements, but we can provide you with some solutions. 

Look at lines 94 to 99 in the RFID.py file. This is the data conversion part that handles writing commands. It converts input strings into corresponding decimal digits. It is then stored in an array, waiting to be written. 

Suppose the command you entered is "write 1 0x0a 0x0b 0x0c 0x0d" (The maximum length of data is 16)， You can do this:

`
data=cmd[2:] 
data=map(lambda x:int(x,16),data)
`

In this way, all 16-digit strings can be converted to 10-digit numbers and written to the chip.

Thanks and good luck to you.

**Comment by sohailahmadsgd** [comment]
Hi
You are awesome
It worked like a charm
Thanks for your help and have a great day
