### ISSUE TITLE
06.2.1 - Alertor.c

### ISSUE THREAD

**Issue by bitbau** [Freenove/Freenove_RFID_Starter_Kit_for_Raspberry_Pi#5]
Getting Error while building:

/usr/bin/ld: /tmp/ccSgTuXA.o: undefined reference to symbol 'sin@@GLIBC_2.4'
//lib/arm-linux-gnueabihf/libm.so.6: error adding symbols: DSO missing from command line

**Comment by SuhaylZhao** [comment]
Hi,

Can you show me a screenshot of where you made a mistake? How did it happen? You give too little information, I can't find the reason accurately.

Thanks.

**Comment by lucasrussell** [comment]
Suck my big ass dick and go fuck yourself  and go fuck your mom

Lucas russell (814) 335-8226

**Comment by bitbau** [comment]
![image](https://user-images.githubusercontent.com/39589216/93298389-74634d80-f7f3-11ea-80da-e7b820fd4f88.png)

**Comment by bitbau** [comment]
![image](https://user-images.githubusercontent.com/39589216/93301259-7a0f6200-f7f8-11ea-8b91-d17224e11210.png)
I got it working by just adding the -lm parameter to the build command

**Comment by SuhaylZhao** [comment]
Hi,

That's right! You're great! 

You are missing some compilation options, which can be found in the tutorial.

![image](https://user-images.githubusercontent.com/3676296/93304338-71864e00-f82f-11ea-82b9-446595c67857.png)

Thanks!
